language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_script: cd server
script:
  - echo "skipping tests"
install: true
deploy:
  provider: heroku
  api_key:
    secure: Hldz75ZcgkuiEsibVrb2tJJygm5ydhGAwzdcWhF1uR9XHiGdboD2MJ21njzT4LYJVuLQjFvJSutyj5WvPNz5V2jtWL8kZV4GoW/lZtLX8LM9Wdh5UX1uMdt95twmZFvvC2YKjxz8m+QnR/w8SYQBEDCgHesvcv5gLwFlTmsb4GtuZf1Z1vbg3UEbGFMO8/itvLYkAPguWyQBDw91CVuZ6Ftm+/sf5r36q5XHiSi0qq0YFabfvlmFeZvO6E5tVTvzBMhzKcNEFVhpKsm2+zc9QMbWJxbKH4ary7ssp5X0tB9GQslTVNJJjpzSwTuycCzUYtbqwu02rtZKUr3Zgi+gv0DqI6GI1L0n3vVJUiJ3K4tcxDiYPuuWrR7sUg79bt/YcO7HACZe6dC4rsUthbP+hPuhQWZDnOrZF4Ms/tLYwYeUqhXgswALBlmWF9gbgUbRCD6BhQXLOxc8XFiVdrjyZIRqsAe2SWrK4UccCCVy+8QjMA5v9t8whhszCnXAghyoqvicDO6u+489JTnBoZCfgOClgiV2KMozsql7Kgz2eGlPRAAHar0MZEf8gFo/6wCtsvnig5Wpq/8uFoGarUfXBxwvWdVOuf4+EAPhT8+b+jgOetF4Z4bmn6VTrkNeY87tIXCN4zpxWZ1ktrKNdfFG/0c10KYsMI9og2nCM3bGdd0=
  app: bcs-buddy
  on:
    repo: zdurham/bcs-buddy
    branch: master
