language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_script: cd server
script:
  - echo "skipping tests"
install: true
deploy:
  provider: heroku
  api_key:
    secure: JA1d1iookQZvIGU4f0PuQq6xeuIOZFzXK66PGIbRsbgWbEcVGPyHHsUgv8Ra0miN5KiIsnO0xMTo1GgC8zeq1YO/mh6U8TEn9RJxCx/NuMyYQL5ttFfDso7RFD8eNE1NZQ8DOEk4NedAJLvKos+iOQRFiXPjR3ssEz6mdUBBmstd9yxBR2XDo5UoOLR8A2+BE8Wpfx3d23p17Q4sIx+miayTpW9pn6nh0nPQu/qB2WfsxgT/TjHbBIqCjost+1Of0x+hgByuFS464VXaabF3PLa/1whPX7kx8ulLjC0YazxXz3wNbzb7EpCWsE3fcltMmOmU7AiInTQ38EvZwFMYxtOHLt4NG9Vkr419dQ8P3gxgfM6PHXcncHk1SnfN2TPGNXS4ItA+lixSckV2GzWsvU8BJ/KRG9Ztzf97jKBfB8NoAh6bADvRmrEhSRKsdxD8vNwWIb1w4NwmkOHZTZkvus9eI9NebOBWhOUAj3Mgl+zd8/2ltpcynTg5+RChbNNgW5HeZ1GgJ1JEmnUh/gwcolyfXqgt8WOz98iDwaQ58x2kQw7DRK3RAiDX1XTObd75nlZy/dZglEqac3kESWr80ZcUNPiIOPut7laYgh2rYZyLlIb1CuirGXU+hCWR/KaOMcH3e5K9QJcTrk8eZFWbMX81GmCGeJKEgfdY8vF66mM=
  app: bcs-buddy
  on:
    repo: zdurham/bcs-buddy
    branch: master
