language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script: cd server
script:
- echo "skipping tests"
install: true
deploy:
  provider: heroku
  api_key:
    secure: SvLNg70Fs1K5o/AoiSDffNQ/seIFrxn855jyWEG0hScch+Jzn2X5gRhGMVySF9jOPOnSJsIJZLSRBzMGTgmt5Sp0GZeb9nLczHdVJ+nDkJKvprCAakZFX5Pdm/93bJRzjsp486J0Jc1h3wZVj8LRzBsDpT5MvctjXy5EpaOLuFJGnjPRazrj/V3y51SOrqWkkZUTEUEx4UlxcjaNjuryCH4iCtcQbt4LXMUdwunkF4orpNgstCSmDXzZ4/ip4opw8dJ7g9cDE902aj5jRrc8FL2emKNQrijOaGIxYCfouD67MFkUhwfHcEGixfdfVYAWxO3/tIakTs5iT1u5PO2Veo8510BJch3YOx7hko+UZ06e8ZUOdoFxRnpCksTZdCmHn67JW+CZEtyCJgWK1uDhuIyKPJg/gVoWMQ1CfLrgo2oPYzPe2eGVyV8e3hLekN3BRMBgMdx/k2dGLCzqlfuaCqdAIR93KptPo2dpdmUBzdEgEJ1i0VpXEQDS9HmBM57oGI7K4rptKBJ+qyilKHDhrNWr6ILQqoiW/N1R+8zmoEypq8908NY+tVp1NX7lQHL8fidPGTr+q3s+7LGk5fWl0ru4xoOeSES5H71b0YTBUYD9cWNu9VhjerH5O8ivILlwePdXJNXWQpLxf1hokLSP8ObAxgqFfgtKZs1v7+d1ElQ=
  app: bcs-buddy
  on:
    repo: zdurham/bcs-buddy
    branch: master
